name: Terraform Azure Deployment
run-name: Deploy to ${{ inputs.environments}} by @${{github.actor}}
on:
  workflow_dispatch:
    inputs:
      environments: 
       description: "choose environment"
       required: true
       default: dev
       type: choice
       options:
        - dev
        - test
        - stg
        - prd
permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: '1.12.2'           # Adjust to your required Terraform version
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-plan :
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Az login
        uses: Azure/login@v2.0.0
        continue-on-error: false
        with:
         creds: '{"clientId":"${{ env.AZURE_CLIENT_ID }}","clientSecret":"${{ env.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ env.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ env.AZURE_TENANT_ID }}"}'

      # Terraform Init
      - name: Terraform Init
        run: terraform init -backend-config="./env/${{ inputs.environments}}/${{ inputs.environments}}.backend.conf"

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate 

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var-file="./env/${{ inputs.environments}}/${{ inputs.environments}}.tfvars"

      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  terraform-apply :
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment:
         name: approval
    steps:
      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      # Terraform Apply - only on main branch
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -var-file="./env/${{ inputs.environments}}/${{ inputs.environments}}.tfvars" -auto-approve
